sudo: required
services:
  - docker #tells the service

before_install:
  - docker build -t tapanmjo528/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tapanmjo528/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-493093635246"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

