sudo: required
services:
  - docker

before_install:
  - docker build -t tapanmjo528/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tapanmjo528/docker-react npm run test -- --coverage
